conky.config = {
    alignment = 'middle_left',
    background = false,
    double_buffer = true,
    no_buffers = true,
    update_interval = 1.0,
    
    own_window = true,
    own_window_transparent = true,
    own_window_type = 'desktop',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    out_to_x = true,
    out_to_wayland = false,
    
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    
    gap_x = 70,
    gap_y = -30,
    
    use_xft = true,
    font = 'Inter:size=12',
    default_color = 'c0caf5',
    color1 = '7aa2f7', -- Tokyo Blue
    color2 = 'bb9af7', -- Tokyo Purple
    color3 = '565f89', -- Tokyo Muted
    color4 = '7dcfff', -- Tokyo Cyan
}

conky.text = [[
${color1}${font Inter Display:size=100:bold}${time %H}${font}
${voffset -35}${color3}${font Inter Display:size=100:bold}${time %M}${font}
${voffset -195}${goto 175}${color2}${font Inter Display:bold:size=38}${time %A}${font}
${voffset 6}${goto 175}${color4}${font Inter:size=22}${time %d %B, %Y}${font}
${voffset 18}${goto 175}${color}${font Inter:italic:size=14}Stay focused. Stay curious.
]]
