conky.config = {
    alignment = 'top_middle',
    background = true,
    double_buffer = true,
    no_buffers = true,
    update_interval = 3600.0, -- Update every hour
    
    own_window = true,
    own_window_transparent = true,
    own_window_type = 'desktop',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    out_to_x = true,
    out_to_wayland = false,
    
    draw_shades = true,
    default_shade_color = '000000',
    draw_outline = false,
    draw_borders = false,
    
    gap_x = 0,
    gap_y = 40, -- Distance from top
    
    use_xft = true,
    font = 'Fira Sans:italic:size=18',
    default_color = 'bb9af7', -- Tokyo Night Purple
}

conky.text = [[
${alignc}"${execi 3600 python3 /home/tontonyuta/.config/conky/quote.py}"
]]
